import type {
  chatbot_attempt_POST,
  chatbot_attempt_message_POST
} from '../post_types';

// The functions below use the API generated by Prisma to interact with the database
async function storeChatAttempt(userId: number, cbmId: number) {
  let attempt: chatbot_attempt_POST = {
    user_id: userId,
    cbm_id: cbmId
  };

  console.log('is running');
  const result = await fetch('api/chatbot-attempts', {
    method: 'POST',
    body: JSON.stringify(attempt)
  });

  console.log('display results please');
  console.log(result);
}

async function storeMessage(
  attemptId: number,
  messageText: string,
  messageType: chatbot_attempt_message_POST['message_type']
) {
  let message: chatbot_attempt_message_POST = {
    attempt_id: attemptId,
    text: messageText,
    message_type: messageType
  };

  console.log(message);
  const result = await fetch('/api/chatbot-messages', {
    method: 'POST',
    body: JSON.stringify(message)
  });

  console.log(result);
}

export { storeChatAttempt, storeMessage };
